name: Test attempt use secret from a fork

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'

jobs:
 test:
    name: Check if I can use a secret to access something I should not be able to
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: coredb-io/app-deploy-dev
          ssh-key: ${{ secrets.SERVICE_USER_GITHUB_SSH_KEY }}
      - name: list
        run: |
          ls
          
          
 test2:
    name: Check if I can initiate a run on a self-hosted github runner that I should not be able to
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: list
        run: |
          ls
          
